sudo: false
language: node_js
node_js:
- '4'
install:
- npm install
- npm run defineKeys
- npm run build
script:
- npm run lint
- mocha --recursive tests/
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy:static'
deploy:
    skip_cleanup: true
    provider: heroku
    api_key:
      secure: process.env.HEROKU_TOKEN
    on: master
    app: kafkatist