sudo: false
language: node_js
node_js:
- '5'
install:
- npm install
- npm run build
- npm run defineKeys
script:
- npm run lint
- mocha --recursive tests/
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy:static'
deploy:
    skip_cleanup: true
    provider: heroku
    api_key:
      secure: $HEROKU_TOKEN
    on: master
    app: kafkatist