sudo: false
language: node_js
node_js:
- '4'
install:
- npm install
- npm run defineKeys
- npm run build
script:
- npm run lint
- npm run test
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy:static'
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: isb8mYdZS23/IxjXtjR2gHHf4gBVf2phcl3mBIDUfiyTi7TlzyEjxWsqxz1Aa4PYXnQM1tQPejBNQn34RtBazjo8rIUXvNm9WuI97+GEbKZmXyisrnIl+a/EuRKC0ijKBNMuQ+Ig56MKDXY+QFhaQO+cAY1B4NkBp5+hComciaskgUuG4NpO78N01V7FdMlMkBWfwSmyZxOhxM78kEuo/OvDJP+KvwAQIdjQAvba52SVPngh7y8ooMLBoxZiUFjlCAdEJmOs7DyNb9pzWOn2oSni5vrjOyKnE5vmntD0Fz6kVjrNgsWpFMaei1zE9ty9WUNXz8xFOhia4jvW1U+7Dgrei9dBVMVCRXV1a5G6lONEFMe16P4cEZ/d/avtygcnyhDuvsrw0XACeZ6QAsCf0eE3hbCY9nxWHvTOMY9V2vFq61Rem1Z7cj5E2SyBVDucQ2UmJ8U0O+DYzESYwQBVcEdxxirUHZDqVDSHgVCIe2C/rysQzvdiv2xarRpo0W1jziYjDcGv74ZSGKFqec0xPUEYYENgxg6yPEsGbFecOXH+J0V58onTNpKoaOmtMF36M5ZDVftLDqh8RSnugjYSkJ7EYrx1KH3EFjGaDXjIan6peWNrokJWFpO4OQegB0h70dJGCD+ZaZulQyaCwEnqlsAquxXEH+rRYR0CTSgc/pQ=
  on: master
  app: kafkatist
env:
  global:
    secure: OneQN+42ebC8tffQI+LkniRCc3IMnFrknu7869Gru9ca2KjP8QcM3DAYjGURvmegYy5UfCpyeGYOa0dB/gxhO3uKIZlFFbMwz8z9KQaay4yUoNgP2ZXkbDX9SgpewsmEaKgD9MsujKPWEKqOzw0S/mAE2qs3B1OCBhmG0kszf8tHg3Yqbh1Agt5U5FusRhlbcpWMjBaMU85noeQpPElPCrK/nLE8ifJSfukIkkfQRHdO09CLBS9m+SASYMXJXBwZtlaTrSgXe3RMTzZX3/uRCAssADcA0IxygISQd3aPknBd6VNK7skI+8lOxgTwy982dXSRgga6wNajEMoRYCloMtP5mIzUooynrvqUnLuIuBNmHDZ6mlGs0Mb0dQaoeN+DLckqlg8bVyPg3qFyk0d9eVLhd2M4SV1TzvRqwyoMUMfepO5nJwdtSUAOzO6TYl7RfInLDyfkgzx5ECQYvAUXgZWUKb8iXrsIdGqISg1y/6E9+SnFEqF0IjDTls42CVnBl1VI8XW1zE8v/Q4mQBkdrpCrVaAr9/L6rvL1F5VUA5I5PgpVe+dlg0770dRqkf0khGl9VEehvENSe0tVAV1V8hydJGCxHHoGaq0ImxgUcnjHY4wFsy28oEjXc/anaNaMTX2YVRCUgzggTkd4Jnn/p2Mczb8dTJFN+CABvdNt2YM=
